import { makeStyles } from '@material-ui/core/styles'
import { cursorTo } from 'readline';

const useStyles = makeStyles(() => ({
  scContainer: {
    position: 'relative',
    marginLeft:'auto',
    marginRight:'auto',
    top: '100px',
    width: '366.17px',
    height: '145px',
  },
  rect174: {
    position: 'absolute',
    left: '1.13%',
    right: '0%',
    top: '15.86%',
    bottom: '28.28%',
    background: '#f9f9fC',
    borderRadius: '8px 8px 0px 0px',
  },
  rect175: {
    position: 'absolute',
    left: '1.13%',
    right: '0%',
    top: '71.72%',
    bottom: '0%',
    background: '#eae8fe',
    borderRadius: '0px 0px 8px 8px',
  },
  profileCard: {
    position: 'absolute',
    left: '0%',
    right: '72.8%',
    top: '0%',
    bottom: '33.79%',
    zIndex: 1,
  },
  group622: {
    position: 'absolute',
    width: '88.75px',
    height: '98px',
    left: '6px',
    top: '-6px',
  },
  scoreChart: {
    position: 'absolute',
    width: '88.75px',
    height: '88.75px',
    left: 'calc(50% - 88.75px/2 + 0.59px)',
    top: 'calc(50% - 88.75px/2 - 0.38px)',
  },
  profileImage: {
    position: 'absolute',
    left: '11%',
    right: '-7.63%',
    top: '8.5%',
    bottom: '-8.65%',
    height: '64px',
    width: '64px'
  },
  contactName: {
    position: 'absolute',
    left: '28.61%',
    right: '25.5%',
    top: '24.83%',
    bottom: '61.38%',
    fontFamily: 'Poppins, sans-serif',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '20px',
    lineHeight: '10px'
  },
  connectionStatus: {
    position: 'absolute',
    left: '28.61%',
    right: '21.94%',
    top: '42.07%',
    bottom: '46.9%',
    fontFamily: 'Poppins, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: '16px',
    lineHeight: '30px',
    color: '#818181',
    mixBlendMode: 'normal',
  },
  exLink: {
    position: 'absolute',
    left: '50px',
    top: '9px',
    fontFamily: 'Poppins, sans-serif',
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: '16px',
    lineHeight: '21px',
    color: '#8463E7',
    mixBlendMode: 'normal',
    cursor: 'pointer'
  },
  btnAdd: {
    position: 'absolute',
    background: '#EAE8FF',
    left: '82.15%',
    right: '5.1%',
    top: '20%',
    bottom: '42.07%',
    color: '#794BFF',
    border: '1px solid #794BFF',
    padding:'8px',
    borderRadius: '6px',
    cursor: 'pointer'
  },
  scoreNumber: {
    position: 'absolute',
    left: '28px',
    top:'-8px',
    width: '27px',
    height: '27px',
    background: '#6A3EEA',
    color: '#fff',
    zIndex: 1,
    fontSize: '13px',
  }
}));

export default useStyles;